name: Pull Request BCheckChecker

on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Validate BChecks
        run: java -jar BCheckChecker-1.5.jar
